In [1]:
import pandas as pd
import numpy as np

In [2]:
cr=pd.read_csv(r"C:\Users\Legion\Desktop\CreditRisk.csv")

In [3]:
cr.shape

(981, 13)

In [4]:
cr.head(5)

Loan_ID Gender Married  Dependents     Education Self_Employed  \
0  LP001002   Male      No         0.0      Graduate            No   
1  LP001003   Male     Yes         1.0      Graduate            No   
2  LP001005   Male     Yes         0.0      Graduate           Yes   
3  LP001006   Male     Yes         0.0  Not Graduate            No   
4  LP001008   Male      No         0.0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

# preprocessing

In [5]:
cr.drop("Loan_ID",axis=1,inplace=True)

In [6]:
cr.isnull().sum()[cr.isnull().sum()>0]

Gender              24
Married              3
Dependents          25
Self_Employed       55
LoanAmount          27
Loan_Amount_Term    20
Credit_History      79
dtype: int64

In [7]:
cr.Self_Employed.value_counts()

No     807
Yes    119
Name: Self_Employed, dtype: int64

In [8]:
cr.Gender.fillna('Male',inplace=True)
cr.Married.fillna('Yes',inplace=True)
cr.Dependents.fillna(cr.Dependents.mean(),inplace=True)
cr.Self_Employed.fillna('No',inplace=True)
cr.LoanAmount.fillna(cr.LoanAmount.mean(),inplace=True)
cr.Loan_Amount_Term.fillna(cr.Loan_Amount_Term.mean(),inplace=True)
cr.Credit_History.fillna(cr.Credit_History.mean(),inplace=True)

In [9]:
cr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 981 entries, 0 to 980
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Gender             981 non-null    object 
 1   Married            981 non-null    object 
 2   Dependents         981 non-null    float64
 3   Education          981 non-null    object 
 4   Self_Employed      981 non-null    object 
 5   ApplicantIncome    981 non-null    int64  
 6   CoapplicantIncome  981 non-null    float64
 7   LoanAmount         981 non-null    float64
 8   Loan_Amount_Term   981 non-null    float64
 9   Credit_History     981 non-null    float64
 10  Property_Area      981 non-null    object 
 11  Loan_Status        981 non-null    object 
dtypes: float64(5), int64(1), object(6)
memory usage: 92.1+ KB


In [10]:
cr.Loan_Status.unique()

array(['Y', 'N'], dtype=object)

In [11]:
cr.Gender.replace({'Male':0, 'Female':1},inplace=True)
cr.Married.replace({'No':0, 'Yes':1},inplace=True)
cr.Education.replace({'Graduate':1, 'Not Graduate':0},inplace=True)
cr.Self_Employed.replace({'No':0, 'Yes':1},inplace=True)
cr.Property_Area.replace({'Urban':1, 'Rural':2, 'Semiurban':3},inplace=True)
cr.Loan_Status.replace({'Y':1, 'N':0},inplace=True)

# train test splite

In [12]:
from sklearn.model_selection import train_test_split
cr_train,cr_test=train_test_split(cr,test_size=.2)

In [13]:
cr_train_x=cr_train.drop(columns=['Loan_Status'],axis=1)
cr_train_y=cr_train["Loan_Status"]

cr_test_x= cr_test.drop(columns=["Loan_Status"],axis=1)
cr_test_y= cr_test["Loan_Status"]

# decision tree

In [14]:
from sklearn.tree import DecisionTreeClassifier
dec=DecisionTreeClassifier()

In [15]:
dec.fit(cr_train_x,cr_train_y)

DecisionTreeClassifier()

In [16]:
pred_train=dec.predict(cr_train_x)
pred_test=dec.predict(cr_test_x)

In [19]:
pred_test

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1],
      dtype=int64)

In [17]:
from sklearn.metrics import confusion_matrix,accuracy_score,f1_score,recall_score,precision_score

In [18]:
mat_test=confusion_matrix(cr_test_y,pred_test)
mat_test

array([[ 37,  23],
       [ 27, 110]], dtype=int64)

In [18]:
accuracy_score(cr_test_y,pred_test)

0.7715736040609137

In [19]:
precision_score(cr_test_y,pred_test)

0.8275862068965517

In [20]:
recall_score(cr_test_y,pred_test)

0.8571428571428571

# decision tree with entropy

In [21]:
from sklearn.tree import DecisionTreeClassifier
dec=DecisionTreeClassifier(criterion="entropy")

In [22]:
dec.fit(cr_train_x,cr_train_y)

DecisionTreeClassifier(criterion='entropy')

In [23]:
dec_pred_ent_test=dec.predict(cr_test_x)

In [24]:
confusion_matrix(cr_test_y,dec_pred_ent_test)

array([[ 31,  26],
       [ 20, 120]], dtype=int64)

In [25]:
accuracy_score(cr_test_y,dec_pred_ent_test)

0.766497461928934

# Random forest

In [26]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()

In [27]:
rfc.fit(cr_train_x,cr_train_y)

RandomForestClassifier()

In [28]:
rfc_pred_train=rfc.predict(cr_train_x)
rfc_pred_test=rfc.predict(cr_test_x)

In [29]:
confusion_matrix(cr_test_y,rfc_pred_test)

array([[ 30,  27],
       [  4, 136]], dtype=int64)

In [30]:
accuracy_score(cr_test_y,rfc_pred_test)

0.8426395939086294

In [31]:
precision_score(cr_test_y,rfc_pred_test)

0.8343558282208589

In [32]:
f1_score(cr_test_y,rfc_pred_test)

0.8976897689768977

In [33]:
recall_score(cr_test_y,rfc_pred_test)

0.9714285714285714

# logistics

In [34]:
from sklearn.linear_model import LogisticRegression
logreg= LogisticRegression()

In [35]:
logreg.fit(cr_train_x,cr_train_y)

C:\Users\admin\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [36]:
logreg_pred_test=logreg.predict(cr_test_x)

In [37]:
confusion_matrix(cr_test_y, logreg_pred_test)

array([[ 28,  29],
       [  1, 139]], dtype=int64)

In [38]:
accuracy_score(cr_test_y, logreg_pred_test)

0.8477157360406091

# Hyperparameter tunning using rfc

In [39]:
from sklearn.model_selection import GridSearchCV

search_dict = {
    'n_estimators': [50, 100, 150], 
    'criterion': ['gini', 'entropy'], 
    'max_depth': [4, 8, 12, 16, 20], 
    'min_samples_split': [50, 60, 70, 80, 90, 100]
}

rfc = RandomForestClassifier()
grid_search = GridSearchCV(rfc, param_grid=search_dict)
grid_search.fit(cr_train_x, cr_train_y)
grid_search.best_params_

{'criterion': 'gini',
 'max_depth': 4,
 'min_samples_split': 60,
 'n_estimators': 150}

In [46]:
from sklearn.ensemble import RandomForestClassifier
rfc =RandomForestClassifier(criterion = 'gini',
 max_depth = 4,
 min_samples_split= 60,
 n_estimators= 150)

In [47]:
rfc.fit(cr_train_x,cr_train_y)

RandomForestClassifier(max_depth=4, min_samples_split=60, n_estimators=150)

In [48]:
pred_test_grid=rfc.predict(cr_test_x)

In [49]:
confusion_matrix(cr_test_y,pred_test_grid)

array([[ 28,  29],
       [  1, 139]], dtype=int64)

In [50]:
accuracy_score(cr_test_y,pred_test_grid)

0.8477157360406091

In [45]:
# Above all the models the Random forest with hyperparameter tuning gives max results

In [51]:
cr=pd.read_csv(r"E:\pythone/CreditRisk.csv")

cr.isnull().sum()[cr.isnull().sum()>0]

cr.Gender.fillna('Male',inplace=True)
cr.Dependents.fillna(0,inplace=True)
cr.Self_Employed.fillna('No',inplace=True)
cr.LoanAmount.fillna(cr.LoanAmount.mean(),inplace=True)
cr.Loan_Amount_Term.fillna(360,inplace=True)
cr.Credit_History.fillna(0,inplace=True)
cr.Married.fillna('Yes',inplace=True)

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

cr.Gender=le.fit_transform(cr.Gender)
cr.Married.replace({'No':0, 'Yes':1},inplace=True)
cr.Education.replace({'Graduate':1, 'Not Graduate':0},inplace=True)
cr.Self_Employed.replace({'No':0, 'Yes':1},inplace=True)
cr.Property_Area=le.fit_transform(cr.Property_Area)
cr.Loan_Status.replace({'Y':1, 'N':0},inplace=True)

#cr1 = cr # just for backup
cr= cr.drop(['Loan_ID'],axis =1)

from sklearn.ensemble import RandomForestClassifier
from boruta import BorutaPy # if error in import then do" pip install boruta
import numpy as np

In [52]:
cr_x =cr.iloc[:,0:11]
cr_x1=cr.iloc[:,0:11]
cr_y = cr.iloc[:,-1]

In [53]:
cr_x =np.array(cr_x)
cr_y =np.array(cr_y)

In [54]:
rf =RandomForestClassifier()
boruta_feature_selector =BorutaPy(rf,max_iter=25,verbose=2)
boruta_feature_selector.fit(cr_x,cr_y)

Iteration: 	1 / 25
Confirmed: 	0
Tentative: 	11
Rejected: 	0
Iteration: 	2 / 25
Confirmed: 	0
Tentative: 	11
Rejected: 	0
Iteration: 	3 / 25
Confirmed: 	0
Tentative: 	11
Rejected: 	0
Iteration: 	4 / 25
Confirmed: 	0
Tentative: 	11
Rejected: 	0
Iteration: 	5 / 25
Confirmed: 	0
Tentative: 	11
Rejected: 	0
Iteration: 	6 / 25
Confirmed: 	0
Tentative: 	11
Rejected: 	0
Iteration: 	7 / 25
Confirmed: 	0
Tentative: 	11
Rejected: 	0
Iteration: 	8 / 25
Confirmed: 	1
Tentative: 	2
Rejected: 	8
Iteration: 	9 / 25
Confirmed: 	1
Tentative: 	2
Rejected: 	8
Iteration: 	10 / 25
Confirmed: 	1
Tentative: 	2
Rejected: 	8
Iteration: 	11 / 25
Confirmed: 	1
Tentative: 	2
Rejected: 	8
Iteration: 	12 / 25
Confirmed: 	1
Tentative: 	2
Rejected: 	8
Iteration: 	13 / 25
Confirmed: 	1
Tentative: 	2
Rejected: 	8
Iteration: 	14 / 25
Confirmed: 	1
Tentative: 	2
Rejected: 	8
Iteration: 	15 / 25
Confirmed: 	1
Tentative: 	2
Rejected: 	8
Iteration: 	16 / 25
Confirmed: 	1
Tentative: 	2
Rejected: 	8
Iteration: 	17 / 25
Confir

BorutaPy(estimator=RandomForestClassifier(n_estimators=1000,
                                          random_state=RandomState(MT19937) at 0x2E8FC658C40),
         max_iter=25, random_state=RandomState(MT19937) at 0x2E8FC658C40,
         verbose=2)

In [55]:
feat_imp =pd.DataFrame()
feat_imp['Fwatures']   =cr_x1.columns
feat_imp['Imp']        = boruta_feature_selector.support_

In [56]:
feat_imp =feat_imp.sort_values('Imp',ascending=False)
feat_imp

Fwatures    Imp
5     ApplicantIncome   True
9      Credit_History   True
0              Gender  False
1             Married  False
2          Dependents  False
3           Education  False
4       Self_Employed  False
6   CoapplicantIncome  False
7          LoanAmount  False
8    Loan_Amount_Term  False
10      Property_Area  False

# conclusion :

in all of this model the random forest is workimg good. 
the maximum  acccuracy , precision, and recall is on random forest
